=== stcorp/procsim/procsim/core/job_order_ESA-EOPG-EEGS-ID-0083.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Created according to ESA-EOPG-EEGS-ID-0083 1.0.-->
<!-- TODO: Attributes! -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Job_Order">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Processor_Configuration">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="File_Class" type="xs:string"/>
              <xs:element name="Processor_Name" type="xs:string"/>
              <xs:element name="Processor_Version" type="xs:string"/>
              <xs:element name="Processing_Node" type="xs:string"/>
              <xs:element name="List_of_Stdout_Log_Levels">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Stdout_Log_Level" minOccurs="0" maxOccurs="5">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="DEBUG"/>
                          <xs:enumeration value="INFO"/>
                          <xs:enumeration value="PROGRESS"/>
                          <xs:enumeration value="WARNING"/>
                          <xs:enumeration value="ERROR"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="List_of_Stderr_Log_Levels">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Stderr_Log_Level" minOccurs="0" maxOccurs="5">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="DEBUG"/>
                          <xs:enumeration value="INFO"/>
                          <xs:enumeration value="PROGRESS"/>
                          <xs:enumeration value="WARNING"/>
                          <xs:enumeration value="ERROR"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Intermediate_Output_Enable" type="xs:boolean"/>
              <xs:element name="Processing_Station" type="xs:string"/>              
              <xs:element name="Request">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="TOI" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Start" type="xs:dateTime"/>              
                          <xs:element name="Stop" type="xs:dateTime"/>              
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="AOI" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Geometry" type="xs:string"/>              
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="List_of_Metadata_Parameters" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Metadata_Parameter" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Name" type="xs:string"/>              
                                <xs:element name="Value" type="xs:string"/>              
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="List_of_Tasks" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Task" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Task_Name" type="xs:token"/>
                    <xs:element name="Task_Version" type="xs:string"/>
                    <xs:element name="Number_of_CPU_Cores" type="xs:float"/>
                    <xs:element name="Amount_of_RAM" type="xs:positiveInteger"/>
                    <xs:element name="Disk_Space" type="xs:positiveInteger"/>
                    <xs:element name="List_of_Proc_Parameters" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Proc_Parameter" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Name" type="xs:string"/>
                                <xs:element name="Value" type="xs:string"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="List_of_Cfg_Files" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Cfg_File" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Cfg_ID" type="xs:string"/>
                                <xs:element name="Cfg_File_Name" type="xs:string"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="List_of_Inputs" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Input" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Input_ID" type="xs:string"/>
                                <xs:element name="Alternative_ID" type="xs:string"/>
                                <xs:element name="List_of_File_Types">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="File_Type" type="xs:string"/>
                                      <xs:element name="List_of_File_Names">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="File_Name" type="xs:string" maxOccurs="unbounded"/>
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="List_of_Outputs" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Output" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="File_Type" type="xs:string"/>
                                <xs:element name="File_Name_Pattern" type="xs:string"/>
                                <xs:element name="File_Dir" type="xs:string" minOccurs="0"/>
                                <xs:element name="Baseline" type="xs:string"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="List_of_Intermediate_Outputs" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Intermediate_Output" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Intermediate_Output_ID" type="xs:string"/>
                                <xs:element name="Intermediate_Output_File" type="xs:string"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="schemaName" type="xs:string" use="required"/>
      <xs:attribute name="schemaVersion" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== stcorp/procsim/test/biomass/joborders/JobOrder.1020.xml
<Job_Order schemaName="ESA-EOPG-EEGS-ID-0083" schemaVersion="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="job_order_ESA-EOPG-EEGS-ID-0083.xsd">
  <Processor_Configuration>
    <File_Class>Todo</File_Class>
    <Processor_Name>l0_ro</Processor_Name>
    <Processor_Version>01.01</Processor_Version>
    <Processing_Node>MyNode</Processing_Node>
    <List_of_Stdout_Log_Levels>
      <Stdout_Log_Level>ERROR</Stdout_Log_Level>
      <Stdout_Log_Level>WARNING</Stdout_Log_Level>
      <Stdout_Log_Level>PROGRESS</Stdout_Log_Level>
      <Stdout_Log_Level>INFO</Stdout_Log_Level>
    </List_of_Stdout_Log_Levels>
    <List_of_Stderr_Log_Levels />
    <Intermediate_Output_Enable>true</Intermediate_Output_Enable>
    <Processing_Station>GAT</Processing_Station>
    <Request />
  </Processor_Configuration>
  <List_of_Tasks>
    <Task>
      <Task_Name>Step2</Task_Name>
      <Task_Version>01.00</Task_Version>
      <Number_of_CPU_Cores>1</Number_of_CPU_Cores>
      <Amount_of_RAM>1073741824</Amount_of_RAM>
      <Disk_Space>1073741824</Disk_Space>
      <List_of_Proc_Parameters>
        <Proc_Parameter>
          <Name>Product_Counter</Name>
          <Value>0</Value>
        </Proc_Parameter>
        <Proc_Parameter>
          <Name>Processing_Stage_Flag</Name>
          <Value>T</Value>
        </Proc_Parameter>
        <Proc_Parameter>
          <Name>originator_ID</Name>
          <Value>TST</Value>
        </Proc_Parameter>
        <Proc_Parameter>
          <Name>Acquisition_Station</Name>
          <Value>ESRIN</Value>
        </Proc_Parameter>
      </List_of_Proc_Parameters>
      <List_of_Cfg_Files />
      <List_of_Inputs>
        <Input>
          <Input_ID />
          <Alternative_ID />
          <List_of_Selected_Inputs>
            <Selected_Input>
              <File_Type>RAWS027_10</File_Type>
              <List_of_File_Names>
                <File_Name>./BIO_RAWS027_10_20210201T002528_20210201T002715_D20210201T013810_00_.{6}.zip</File_Name>
              </List_of_File_Names>
            </Selected_Input>
          </List_of_Selected_Inputs>
        </Input>
        <Input>
          <Input_ID />
          <Alternative_ID />
          <List_of_Selected_Inputs>
            <Selected_Input>
              <File_Type>RAWS028_10</File_Type>
              <List_of_File_Names>
                <File_Name>./BIO_RAWS028_10_20210201T002528_20210201T002715_D20210201T013810_00_.{6}.zip</File_Name>
              </List_of_File_Names>
            </Selected_Input>
          </List_of_Selected_Inputs>
        </Input>
        <Input>
          <Input_ID />
          <Alternative_ID />
          <List_of_Selected_Inputs>
            <Selected_Input>
              <File_Type>RAWS023_10</File_Type>
              <List_of_File_Names>
                <File_Name>./BIO_RAWS023_10_20210201T000000_20210201T013810_D20210201T013810_00_.{6}.zip</File_Name>
              </List_of_File_Names>
            </Selected_Input>
          </List_of_Selected_Inputs>
        </Input>
        <Input>
          <Input_ID />
          <Alternative_ID />
          <List_of_Selected_Inputs>
            <Selected_Input>
              <File_Type>RAWS024_10</File_Type>
              <List_of_File_Names>
                <File_Name>./BIO_RAWS024_10_20210201T000000_20210201T013810_D20210201T013810_00_.{6}.zip</File_Name>
              </List_of_File_Names>
            </Selected_Input>
          </List_of_Selected_Inputs>
        </Input>
      </List_of_Inputs>
      <List_of_Outputs>
        <Output>
          <File_Type>RO_RAW__0S</File_Type>
          <File_Name_Pattern />
          <File_Dir>./</File_Dir>
          <Baseline>00</Baseline>
        </Output>
        <Output>
          <File_Type>RO_RAWP_0M</File_Type>
          <File_Name_Pattern />
          <File_Dir>./</File_Dir>
          <Baseline>00</Baseline>
        </Output>
      </List_of_Outputs>
      <List_of_Intermediate_Outputs>
        <Intermediate_Output>
          <Intermediate_Output_ID>1</Intermediate_Output_ID>
          <Intermediate_Output_File>./tempfile_1</Intermediate_Output_File>
        </Intermediate_Output>
        <Intermediate_Output>
          <Intermediate_Output_ID>2</Intermediate_Output_ID>
          <Intermediate_Output_File>./tempfile_2</Intermediate_Output_File>
        </Intermediate_Output>
      </List_of_Intermediate_Outputs>
    </Task>
    <Task>
      <Task_Name>Step3</Task_Name>
      <Task_Version>01.00</Task_Version>
      <Number_of_CPU_Cores>1</Number_of_CPU_Cores>
      <Amount_of_RAM>1073741824</Amount_of_RAM>
      <Disk_Space>1073741824</Disk_Space>
      <List_of_Proc_Parameters>
        <Proc_Parameter>
          <Name>Product_Counter</Name>
          <Value>0</Value>
        </Proc_Parameter>
        <Proc_Parameter>
          <Name>Processing_Stage_Flag</Name>
          <Value>T</Value>
        </Proc_Parameter>
        <Proc_Parameter>
          <Name>originator_ID</Name>
          <Value>TST</Value>
        </Proc_Parameter>
        <Proc_Parameter>
          <Name>Acquisition_Station</Name>
          <Value>ESRIN</Value>
        </Proc_Parameter>
      </List_of_Proc_Parameters>
      <List_of_Cfg_Files />
      <List_of_Inputs>
        <Input>
          <Input_ID />
          <Alternative_ID />
          <List_of_Selected_Inputs>
            <Selected_Input>
              <File_Type>RO_RAWP_0M</File_Type>
              <List_of_File_Names>
                <File_Name>./.*RO_RAWP_0M.*</File_Name>
              </List_of_File_Names>
            </Selected_Input>
          </List_of_Selected_Inputs>
        </Input>
      </List_of_Inputs>
      <List_of_Outputs>
        <Output>
          <File_Type>RO_RAW__0M</File_Type>
          <File_Name_Pattern />
          <File_Dir>./</File_Dir>
          <Baseline>00</Baseline>
        </Output>
      </List_of_Outputs>
      <List_of_Intermediate_Outputs>
        <Intermediate_Output>
          <Intermediate_Output_ID>1</Intermediate_Output_ID>
          <Intermediate_Output_File>./tempfile_1</Intermediate_Output_File>
        </Intermediate_Output>
        <Intermediate_Output>
          <Intermediate_Output_ID>2</Intermediate_Output_ID>
          <Intermediate_Output_File>./tempfile_2</Intermediate_Output_File>
        </Intermediate_Output>
      </List_of_Intermediate_Outputs>
    </Task>
    <Task>
      <Task_Name>Step4</Task_Name>
      <Task_Version>01.00</Task_Version>
      <Number_of_CPU_Cores>1</Number_of_CPU_Cores>
      <Amount_of_RAM>1073741824</Amount_of_RAM>
      <Disk_Space>1073741824</Disk_Space>
      <List_of_Proc_Parameters>
        <Proc_Parameter>
          <Name>Product_Counter</Name>
          <Value>0</Value>
        </Proc_Parameter>
        <Proc_Parameter>
          <Name>Processing_Stage_Flag</Name>
          <Value>T</Value>
        </Proc_Parameter>
        <Proc_Parameter>
          <Name>originator_ID</Name>
          <Value>TST</Value>
        </Proc_Parameter>
        <Proc_Parameter>
          <Name>Acquisition_Station</Name>
          <Value>ESRIN</Value>
        </Proc_Parameter>
      </List_of_Proc_Parameters>
      <List_of_Cfg_Files />
      <List_of_Inputs>
        <Input>
          <Input_ID />
          <Alternative_ID />
          <List_of_Selected_Inputs>
            <Selected_Input>
              <File_Type>RO_RAW__0M</File_Type>
              <List_of_File_Names>
                <File_Name>./.*RO_RAW__0M.*</File_Name>
              </List_of_File_Names>
            </Selected_Input>
          </List_of_Selected_Inputs>
        </Input>
        <Input>
          <Input_ID />
          <Alternative_ID />
          <List_of_Selected_Inputs>
            <Selected_Input>
              <File_Type>RAWS022_10</File_Type>
              <List_of_File_Names>
                <File_Name>./BIO_RAWS022_10_20210201T000000_20210201T013810_D20210201T013810_00_??????.zip</File_Name>
              </List_of_File_Names>
            </Selected_Input>
          </List_of_Selected_Inputs>
        </Input>
      </List_of_Inputs>
      <List_of_Outputs>
        <Output>
          <File_Type>AC_RAW__0A</File_Type>
          <File_Name_Pattern />
          <File_Dir>./</File_Dir>
          <Baseline>00</Baseline>
        </Output>
      </List_of_Outputs>
      <List_of_Intermediate_Outputs>
        <Intermediate_Output>
          <Intermediate_Output_ID>1</Intermediate_Output_ID>
          <Intermediate_Output_File>./tempfile_1</Intermediate_Output_File>
        </Intermediate_Output>
        <Intermediate_Output>
          <Intermediate_Output_ID>2</Intermediate_Output_ID>
          <Intermediate_Output_File>./tempfile_2</Intermediate_Output_File>
        </Intermediate_Output>
      </List_of_Intermediate_Outputs>
    </Task>
  </List_of_Tasks>
</Job_Order>
